- package.json
>
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
Fixes #
```release-note
```
```docs
```
> .com not .org

- README.md
- package-lock.json
- package.json
- src/app.js
- src/controllers/token.js
- src/router.js
- src/tests/token.test.js
- src/tests/utils/samples.js
- src/utils/jwt_secret.js
- src/utils/token_generator.js
/kind feature
- Creates route POST /token to generate a valid JWT token
- Allows to change the JWT secret using an environment variable
Fixes #
```release-note
- New route POST /token
- Change JWT secret using JWT_KEY as environment variable
```
```docs
- POST /token
-- information in request body will be added to payload 
-- actor_id and claims will be created if not specified in the request body
-- secret used can be changed using "x-secret" in header
-- token duration can be changed using "x-duration" in header
- To change the secret, use JWT_KEY …
```
> Route to generate JWT token; possibility to change JWT secret in .env

- src/controllers/state.js
- src/nodes/createIndexNode.js
- src/nodes/createUuidNode.js
- src/nodes/retrieveProcessNode.js
- src/nodes/tokenizeNode.js
- src/nodes/validateSchemaNode.js
- src/routers/mainRouter.js
/kind feature
Add 2 new routes:
1. Retrieve the nodeSpec for the specified state (GET /states/:id/spec)
2. Calculate the execution data of the specified state (GET /states/:id/execution)
```release-note
```
```docs
```
> Fbs 53 calcular a execucao de um no

- src/validators/workflow.js
/kind bug
Force a toLowerCase into node type validation
Fixes #69 
```release-note
NONE
```
```docs
```
> fix: force type toLowerCase

- src/routers/cockpitRouter.js
/kind bug
Fix a broken dep on v2.5.4
Fixes #
```release-note
```
```docs
```
> fix(routers): remove testMapper

- package-lock.json
- package.json
/kind bug
Fix error message on StartProcess Node when the workflow_name provided is non-existant.
Fixes #
```release-note
```
```docs
```
> fix: fix result on startProcess node

- package-lock.json
- src/nodes/basicAuthNode.js
/kind feature
Add environment variables for the basicAuth node keys.
Fixes #
```release-note
```
```docs
```
> feat: add environment variables for basicAuth node keys

- db/migrations/20221018153215_create_trigger_table.js
- db/migrations/20221020185714_create_target_table.js
- db/migrations/20221025130847_create_trigger_target_table.js
- package-lock.json
- package.json
feature
Updates flowbuild engine version with signal nodes feature
No public issue
```release-note
New category for Finish and Start nodes
```
```docs
Finish:
"category": "signal",
"parameters": {
"signal": "test_signal",
"input": {
"anyKey": "anyValue"
}
}
Start:
"category": "signal",
"parameters": {
"signal": "signal_target_workflow",
"input_schema": {}
}
```
> feat: updates flowbuild engine version with signal nodes

- package-lock.json
- package.json
>
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
Fixes #
```release-note
```
```docs
```
> fix: updates engine version with fix for node parameters

- .github/workflows/release-auto-pr.yml
/kind bug
Update release gitAction
Fixes #
```release-note
```
```docs
```
> ci: update create pull request version to v4

- package-lock.json
- package.json
/kind bug
Fix a typo on process class that prevent the application from starting.
Fixes #
```release-note
```
```docs
```
> fix: fix typo on finish node process

- knexfile.js
/kind feature
Add pool configuration to knex
Fixes #
```release-note
```
```docs
```
> feat: add pool config to prod

- src/nodes/filterDataNode.js
Melhoria no custom node filterData para aceitar um objeto de arrays no parametro de primary_keys
> feat: adjust to receive object from array on primary keys

- db/migrations/20221209134026_create_switch_table.js
- package-lock.json
- package.json
feature
Fixes #
```release-note
```
```docs
```
> chore: updates engine version to 2.18.0-beta.2

- README.md
>
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
Fixes #
```release-note
```
```docs
```
> feat: forcing version update

- package-lock.json
- package.json
>
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
Fixes #
```release-note
```
```docs
```
> feat: updates engine version to 2.19.0-beta.2

- package-lock.json
- package.json
bug
Fixes #
```release-note
```
```docs
```
> fix: updates engine version to resolve issue

- package-lock.json
- package.json
bug
Fixes #
```release-note
```
```docs
```
> fix: updates engine with http node payload fix

- .github/workflows/pr-validation.yml
- package.json
- src/tests/activityManager.test.js
- src/tests/activityManagerValidation.test.js
- src/tests/cockpitBlueprintValidation.test.js
- src/tests/cockpitProcesses.test.js
- src/tests/cockpitWorkflows.test.js
- src/tests/grpcNode.test.js
- src/tests/healthCheck.test.js
- src/tests/indexer.test.js
- src/tests/package.test.js
- src/tests/process.test.js
- src/tests/token.test.js
- src/tests/utils/auxiliar.js
- src/tests/utils/fixtures.js
- src/tests/utils/requestConfig.js
- src/tests/workflow.test.js
/kind bug
Fixes unit tests instability
**What to know**:
There was an inconsistency among tear down fixtures across all test files, which cause them to display unpredictable behavior. This PR refactor the tear down fixture into a new file `fixtures.js`, so all tests should display a predictable result. This also decreases the amount of duplicated code among test files 
```release-note
NONE
```
_Unit tests are back in town_
> Fix unit tests execution

- README.md
- src/services/mqtt.js
/kind feature
adds username and password to mqtt broker connection.
Fixes #
```release-note
```
```docs
```
> fix: add username and password to mqtt broker connection

- .github/workflows/pr-validation.yml
- README.md
- package-lock.json
- package.json
- src/app.js
- src/services/mqtt.js
- src/tests/activityManager.test.js
- src/tests/activityManagerValidation.test.js
- src/tests/cockpitBlueprintValidation.test.js
- src/tests/cockpitProcesses.test.js
- src/tests/cockpitWorkflows.test.js
- src/tests/grpcNode.test.js
- src/tests/healthCheck.test.js
- src/tests/indexer.test.js
- src/tests/package.test.js
- src/tests/process.test.js
- src/tests/token.test.js
- src/tests/utils/auxiliar.js
- src/tests/utils/fixtures.js
- src/tests/utils/requestConfig.js
- src/tests/workflow.test.js
feature
Fixes #
```release-note
```
```docs
```
> feat: adds warn logs to http node on beta version

- package-lock.json
- package.json
- src/app.js
feature
Updates engine to version with HTTP warn logs and sets default LOG_LEVEL to 'warn'
Fixes #
```release-note
```
```docs
```
> feat: adds warn logs to http node

- src/nodes/remapDataNode.js
- src/tests/remapDataNode.test.js
Melhoria no customNode remapData para aceitar objetos aninhados no `dictionary`.
> feat: add possibility to get nested objects on dictionary

- .github/workflows/auto-merge-release-bump.yml
- .github/workflows/first-time-contrib.yml
- .github/workflows/pr-validation.yml
- .github/workflows/release-auto-pr.yml
- package-lock.json
/kind cleanup
```release-note
NONE
```
> Upgrade node version in CI pipeline to 18

- src/utils/engineListener.js
/kind bugfix
**What this PR does / why we need it:**
Fix the topic key on mqtt that was breaking when publishing a message on the topic based on actor_id and session_id.
> fix: adjust mqtt topic key

- knexfile.js
/kind bug
Add SSL property to knexfile to allow secure connections to database (p.ex.: NeonDb)
Fixes #
```release-note
```
```docs
```
> fix: :card_file_box: add ssl property to prod knex config

- src/utils/engineListener.js
- src/utils/engineLogger.js
/kind fix
**What this PR does / why we need it:**
Set broker default to MQTT on publishing message.
Adjust option to send message only on creation.
**Which issue(s) this PR fixes:
Special notes for your reviewer:
Does this PR introduce a user-facing change?:**
**Additional documentation e.g., usage docs, etc.:**
> fix: set broker default to MQTT

- package-lock.json
- package.json
/kind fix
**What this PR does / why we need it:**
Update engine version to adjust continue process method.
**Which issue(s) this PR fixes:
Special notes for your reviewer:
Does this PR introduce a user-facing change?:**
**Additional documentation e.g., usage docs, etc.:**
> fix: update engine to adjust continue process

- README.md
documentation
Updates README
Fixes #
```release-note
```
```docs
```
> docs: updates README

- src/middlewares/actordata.js
/kind bug
Change the actordata middleware to include in exData all non-default properties available in the token payload.
Key selection can still be done thru JWT_EXTRA_KEYS variable.
Fixes #
```release-note
NONE
```
```docs
```
> fix(middlewares): add by default all token keys to extData

- src/controllers/cockpit/process.js
- src/routers/cockpitRouter.js
feature
Adds route 
/cockpit/processes/2d5e26f0-e9de-11ed-b41e-e1f5275992ea/historyExecution
Fixes #
```release-note
Should wait for new version from engine
```
```docs
It allows usage of fromStep QS:
/cockpit/processes/2d5e26f0-e9de-11ed-b41e-e1f5275992ea/execution?fromStep=1
Should return object as the one below:
{
"current_status": "finished",
"max_step_number": 3,
"execution": [
{
"node_id": "END",
"last_created_at": "2023-05-03T18:13:17.193Z",
"last_status": "finished",
"step_numbers": [
3
]
},
{
"node_id": "START",
"last_created_at": …
```
> feat: (WIP) adds historyExecution route on cockpit router

- src/controllers/state.js
- src/routers/mainRouter.js
feature
Adds new routes to return state execution context
Fixes #
```release-note
Needs to wait for new engine version to be released
```
```docs
route /states/:state_id/context:
Response:
{
"stepNumber": 3,
"previousState": {
"id": "65aefd60-ea9f-11ed-b142-693f623b3f2d",
"created_at": "2023-05-04T17:16:24.502Z",
"process_id": "65a78350-ea9f-11ed-b142-693f623b3f2d",
"step_number": 2,
"node_id": "START",
"next_node_id": "END",
"bag": {
"userId": "e45e5021-16a4-4450-8018-35f0aadc0b31"
},
"external_input": {},
"result": {
"step_number": 2
},
"error": …
```
> feat: (WIP) adds new routes to fetch state execution context

- package-lock.json
- package.json
bug
Updates package to attend to /diagram routes errors
Fixes #
```release-note
```
```docs
```
> fix: updates '@flowbuild/nodejs-diagram-builder' package version

- package-lock.json
- package.json
feature
Update engine to avoid abort & expire process to generate process state without bag.
Fixes #
```release-note
```
```docs
```
> feat: update engine to abort & expire process keep bag on state

- src/utils/engineListener.js
feature
Adds more data to processStateListener to emit to the brokers.
Fixes #
```release-note
```
```docs
```
> feature: adds extra data on state message to brokers

- src/controllers/connection.js
feature
changes kafka beacon topic
(just in case we need it to better test while we can't create new topics) 
Fixes #
```release-note
```
```docs
```
> feat: changes topic used to publish KAFKA beacon message

- db/migrations/20230516151924_create_environment_variable_table.js
- package-lock.json
- package.json
- src/controllers/cockpit/environmentVariable.js
- src/controllers/workflow.js
- src/routers/cockpitRouter.js
- src/tests/cockpitEnvironmentVariable.test.js
- src/tests/utils/auxiliar.js
- src/validators/base.js
- src/validators/cockpit.js
- src/validators/workflow.js
/kind feature
Add /cockpit/envs routes
Update engine
Fixes #
Needs to wait the merge of https://github.com/flow-build/engine/pull/291 from engine to be merged.
```release-note
```
```docs
```
> feat: add /cockpit/envs routes

- package-lock.json
- package.json
>
> /kind fix
Fixes #
```release-note
```
```docs
```
> fix: updates engine version to 2.32.1 to remove unecessary bp validation
